-- Seed the former app-local plaza detail cards into the backend feed.
-- The rows are skipped when an environment has no auth users yet, because
-- community_posts.author_id is intentionally tied to auth.users.

DO $$
DECLARE
  seed_author_id UUID;
BEGIN
  SELECT id
    INTO seed_author_id
  FROM auth.users
  WHERE email = 'dev.test@artsee.app'
  LIMIT 1;

  IF seed_author_id IS NULL THEN
    SELECT id
      INTO seed_author_id
    FROM auth.users
    ORDER BY created_at
    LIMIT 1;
  END IF;

  IF seed_author_id IS NULL THEN
    RAISE NOTICE 'Skipping plaza legacy seed: no auth users found.';
    RETURN;
  END IF;

  INSERT INTO public.community_posts (
    id,
    author_id,
    title,
    body,
    image_urls,
    status,
    audit_status,
    audit_provider,
    audit_reason,
    audit_metadata,
    audited_at,
    like_count,
    comment_count,
    view_count,
    save_count,
    metadata,
    created_at,
    updated_at
  )
  VALUES
  (
    '11111111-1111-4111-8111-111111111101',
    seed_author_id,
    '花 60 万读艺术留学，真的买到未来了吗？',
    '预算、城市、作品集和家庭期待被放在同一张桌上。',
    '{}'::text[],
    'published',
    'approved',
    'seed',
    NULL,
    '{"source":"migration"}'::jsonb,
    now(),
    186,
    742,
    18600,
    0,
    $json${
      "surface":"plaza",
      "source":"plaza_legacy",
      "legacy_type":"debate_topic",
      "kind":"debate",
      "channel":"留学账本",
      "track":"申请向",
      "category":"艺术留学",
      "status_label":"进行中",
      "time_left":"剩 2 天",
      "lead":"预算、城市、作品集和家庭期待被放在同一张桌上。",
      "pro":"名校网络和海外经历很难用短期薪资衡量",
      "con":"如果只是换一个更贵的焦虑场，不如先停下来算账",
      "pro_percent":62,
      "heat_label":"18.6k",
      "comments_label":"742",
      "floor":"38 楼",
      "hot_comment":"“最贵的不是学费，是不知道自己为什么出国。”",
      "pro_comment":"城市资源和同行网络会改变一个人的长期半径。",
      "con_comment":"如果目标不清楚，贵学校只会放大原来的焦虑。",
      "agent_persona":"现实派老学长",
      "agent_reply":"钱确实不是唯一答案，但你愿意把回报周期拉到几年？",
      "ask_seed":"花 60 万读艺术留学，怎样判断它到底值不值？",
      "tags":["预算","回报","家庭决策"],
      "icon":"wallet",
      "accent":"#D59D2B"
    }$json$::jsonb,
    '2026-07-07T12:00:00Z',
    '2026-07-07T12:00:00Z'
  ),
  (
    '11111111-1111-4111-8111-111111111102',
    seed_author_id,
    '侠之大者，为国为民',
    '金庸小说神句正在被重新打分，大家更在意立意还是文采。',
    '{}'::text[],
    'published',
    'approved',
    'seed',
    NULL,
    '{"source":"migration"}'::jsonb,
    now(),
    557,
    1160,
    9800,
    0,
    $json${
      "surface":"plaza",
      "source":"plaza_legacy",
      "legacy_type":"rating_item",
      "kind":"rating",
      "collection":"金句口碑",
      "subtitle":"金庸小说神句正在被重新打分，大家更在意立意还是文采。",
      "quote":"“并不是成为大侠的人，就会被大家所认可，而是...”",
      "score":"9.9",
      "rating_count":"1160",
      "likes_label":"557",
      "comments_label":"1160",
      "source_label":"金庸小说神句小组",
      "time_label":"今天12:08",
      "cover_seed":"jinyong_quote_artsee",
      "accent":"#06A5B8",
      "replies":[
        {"author":"小黑屋住户","date":"2026-07-06","body":"并不是成为大侠的人，就会被大家所认可，而是被大家所认可的人，才能成为大侠。","likes":122,"avatar_color":"#D59D2B"},
        {"author":"CLANNADOR","date":"2026-07-06","body":"记得最早的时候是“为国为民，侠之大者”，不知道为什么换个顺序以后更像一种责任。","likes":88,"avatar_color":"#1A9B7A"},
        {"author":"月下看书","date":"2026-07-06","body":"这句好在不只是热血，它把被认可和成为谁这两件事反过来问了一遍。","likes":64,"avatar_color":"#0F3C8C"}
      ]
    }$json$::jsonb,
    '2026-07-07T11:55:00Z',
    '2026-07-07T11:55:00Z'
  ),
  (
    '11111111-1111-4111-8111-111111111103',
    seed_author_id,
    'AI 参与作品集，到底是新能力还是作弊？',
    '工具边界、原创表达和院校审核规则正在互相追赶。',
    '{}'::text[],
    'published',
    'approved',
    'seed',
    NULL,
    '{"source":"migration"}'::jsonb,
    now(),
    123,
    516,
    12300,
    0,
    $json${
      "surface":"plaza",
      "source":"plaza_legacy",
      "legacy_type":"debate_topic",
      "kind":"debate",
      "channel":"AI 作品集",
      "track":"申请向",
      "category":"作品集",
      "status_label":"进行中",
      "time_left":"剩 5 小时",
      "lead":"工具边界、原创表达和院校审核规则正在互相追赶。",
      "pro":"会用 AI 是未来创作能力的一部分",
      "con":"只会生成结果，作品集会失去判断力",
      "pro_percent":48,
      "heat_label":"12.3k",
      "comments_label":"516",
      "floor":"21 楼",
      "hot_comment":"“AI 不可怕，可怕的是你说不清每一步为什么。”",
      "pro_comment":"AI 像摄影机一样，是新工具，不该天然被判作弊。",
      "con_comment":"作品集评的是判断力，不是把提示词包装成作者性。",
      "agent_persona":"理想派策展人",
      "agent_reply":"我先同意工具无罪，但你能解释每张图为什么这样生成吗？",
      "ask_seed":"AI 参与作品集时，哪些环节应该主动说明？",
      "tags":["AI","原创性","院校审核"],
      "icon":"auto_fix",
      "accent":"#8D6AE8"
    }$json$::jsonb,
    '2026-07-07T11:50:00Z',
    '2026-07-07T11:50:00Z'
  ),
  (
    '11111111-1111-4111-8111-111111111104',
    seed_author_id,
    '作品集机构是在救命，还是在制造焦虑？',
    '好服务和高压销售之间，用户需要可讨论的判断标准。',
    '{}'::text[],
    'published',
    'approved',
    'seed',
    NULL,
    '{"source":"migration"}'::jsonb,
    now(),
    94,
    389,
    9400,
    0,
    $json${
      "surface":"plaza",
      "source":"plaza_legacy",
      "legacy_type":"debate_topic",
      "kind":"debate",
      "channel":"机构实话",
      "track":"申请向",
      "category":"作品集",
      "status_label":"进行中",
      "time_left":"剩 1 天",
      "lead":"好服务和高压销售之间，用户需要可讨论的判断标准。",
      "pro":"时间线、材料和导师反馈能把混乱变成路径",
      "con":"过度包装让学生越来越不像自己",
      "pro_percent":55,
      "heat_label":"9.4k",
      "comments_label":"389",
      "floor":"57 楼",
      "hot_comment":"“好的机构应该让你更清醒，不是更依赖。”",
      "pro_comment":"不是每个学生都有成熟的信息源，外部结构很重要。",
      "con_comment":"一旦故事线被代写，学生反而丢掉自己的声音。",
      "agent_persona":"数据派顾问",
      "agent_reply":"先别站队，我想看合同、导师频次和修改记录再判断。",
      "ask_seed":"怎么判断作品集机构是在帮我，而不是制造焦虑？",
      "tags":["机构","避坑","导师反馈"],
      "icon":"forum",
      "accent":"#E16F5C"
    }$json$::jsonb,
    '2026-07-07T11:45:00Z',
    '2026-07-07T11:45:00Z'
  ),
  (
    '11111111-1111-4111-8111-111111111105',
    seed_author_id,
    '越是好看的女人越会骗人',
    '一条带点戏谑的短评被反复引用，大家在给语气、记忆点和表达力度打分。',
    '{}'::text[],
    'published',
    'approved',
    'seed',
    NULL,
    '{"source":"migration"}'::jsonb,
    now(),
    312,
    704,
    7600,
    0,
    $json${
      "surface":"plaza",
      "source":"plaza_legacy",
      "legacy_type":"rating_item",
      "kind":"rating",
      "collection":"作品口碑",
      "subtitle":"一条带点戏谑的短评被反复引用，大家在给语气、记忆点和表达力度打分。",
      "quote":"“贯穿了全书，殷素素看人真准（）”",
      "score":"9.7",
      "rating_count":"704",
      "likes_label":"312",
      "comments_label":"704",
      "source_label":"高赞短评小组",
      "time_label":"昨天21:16",
      "cover_seed":"artsee_comment_memory",
      "accent":"#0B9FB3",
      "replies":[
        {"author":"一口气读完","date":"2026-07-06","body":"这类短评最有意思的是，一句话能把角色关系、读者记忆和一点玩笑都塞进去。","likes":73,"avatar_color":"#E16F5C"},
        {"author":"不想写长评","date":"2026-07-06","body":"比起严肃解读，我反而更喜欢这种像朋友突然补刀一样的评论。","likes":45,"avatar_color":"#8D6AE8"},
        {"author":"旧书页","date":"2026-07-06","body":"能被记住的评论，往往不是最完整的，而是最有现场感的。","likes":39,"avatar_color":"#1A9B7A"}
      ]
    }$json$::jsonb,
    '2026-07-07T11:40:00Z',
    '2026-07-07T11:40:00Z'
  ),
  (
    '11111111-1111-4111-8111-111111111106',
    seed_author_id,
    'AI 生成的图，算不算艺术？',
    '当创作从手艺变成选择，作者性还站得住吗？',
    '{}'::text[],
    'published',
    'approved',
    'seed',
    NULL,
    '{"source":"migration"}'::jsonb,
    now(),
    151,
    681,
    15100,
    0,
    $json${
      "surface":"plaza",
      "source":"plaza_legacy",
      "legacy_type":"debate_topic",
      "kind":"debate",
      "channel":"AI 艺术审判",
      "track":"文化向",
      "category":"艺术讨论",
      "status_label":"进行中",
      "time_left":"剩 3 天",
      "lead":"当创作从手艺变成选择，作者性还站得住吗？",
      "pro":"艺术的核心是观念和选择，不是工具是否亲手完成",
      "con":"没有身体经验和持续训练，图像再漂亮也只是结果",
      "pro_percent":57,
      "heat_label":"15.1k",
      "comments_label":"681",
      "floor":"9 楼",
      "hot_comment":"“摄影刚出现时也被骂过不像艺术。”",
      "pro_comment":"如果杜尚能把现成品送进美术馆，AI 图也该被讨论。",
      "con_comment":"问题不是工具新，而是很多作品没有必要性。",
      "agent_persona":"杠精策展人",
      "agent_reply":"我承认 AI 可以是艺术，但你能说清作者到底做了什么吗？",
      "ask_seed":"AI 生成的图算艺术吗？判断标准应该是什么？",
      "tags":["AI 艺术","作者性","审美"],
      "icon":"auto_awesome",
      "accent":"#1A9B7A"
    }$json$::jsonb,
    '2026-07-07T11:35:00Z',
    '2026-07-07T11:35:00Z'
  ),
  (
    '11111111-1111-4111-8111-111111111107',
    seed_author_id,
    '策展人的解读，是帮助理解还是过度包装？',
    '墙上的文字、作品本身和观众直觉正在互相争夺解释权。',
    '{}'::text[],
    'published',
    'approved',
    'seed',
    NULL,
    '{"source":"migration"}'::jsonb,
    now(),
    89,
    304,
    8900,
    0,
    $json${
      "surface":"plaza",
      "source":"plaza_legacy",
      "legacy_type":"debate_topic",
      "kind":"debate",
      "channel":"展览现场",
      "track":"文化向",
      "category":"艺术讨论",
      "status_label":"进行中",
      "time_left":"剩 8 小时",
      "lead":"墙上的文字、作品本身和观众直觉正在互相争夺解释权。",
      "pro":"好的解读给观众入口，不是所有人都熟悉艺术史语境",
      "con":"太多解释会替作品说话，把观看变成背答案",
      "pro_percent":46,
      "heat_label":"8.9k",
      "comments_label":"304",
      "floor":"31 楼",
      "hot_comment":"“门槛可以有，但别把门槛包装成优越感。”",
      "pro_comment":"没有背景信息，很多作品会被误解成装置摆拍。",
      "con_comment":"如果离开小作文就不成立，作品本身可能不够有力。",
      "agent_persona":"展厅嘴替",
      "agent_reply":"我先站反方一点：你看作品时真的需要先读完那块墙吗？",
      "ask_seed":"策展文字到底是在帮助观看，还是在替作品找借口？",
      "tags":["看展","策展","公共审美"],
      "icon":"visibility",
      "accent":"#0F3C8C"
    }$json$::jsonb,
    '2026-07-07T11:30:00Z',
    '2026-07-07T11:30:00Z'
  ),
  (
    '11111111-1111-4111-8111-111111111108',
    seed_author_id,
    '丑东西火了，是审丑还是真的审美变了？',
    '从丑萌、土酷到低保真视觉，年轻人的审美词典正在改写。',
    '{}'::text[],
    'published',
    'approved',
    'seed',
    NULL,
    '{"source":"migration"}'::jsonb,
    now(),
    107,
    427,
    10700,
    0,
    $json${
      "surface":"plaza",
      "source":"plaza_legacy",
      "legacy_type":"debate_topic",
      "kind":"debate",
      "channel":"审美围观",
      "track":"文化向",
      "category":"艺术讨论",
      "status_label":"已归档",
      "time_left":"查看复盘",
      "lead":"从丑萌、土酷到低保真视觉，年轻人的审美词典正在改写。",
      "pro":"审美本来会反叛精致，丑感也是时代情绪",
      "con":"很多所谓丑美学只是营销给平庸找台阶",
      "pro_percent":64,
      "heat_label":"10.7k",
      "comments_label":"427",
      "floor":"66 楼",
      "hot_comment":"“不是丑赢了，是标准答案失效了。”",
      "pro_comment":"反精致也是一种表达，不能只用学院标准判断。",
      "con_comment":"如果所有粗糙都被叫真诚，审美就不用训练了。",
      "agent_persona":"毒舌评论员",
      "agent_reply":"这题我差点被正方说服，但粗糙和有意为之仍然不同。",
      "ask_seed":"丑美学流行，是审美更新还是营销包装？",
      "tags":["审美","青年文化","视觉趋势"],
      "icon":"palette",
      "accent":"#E16F5C"
    }$json$::jsonb,
    '2026-07-07T11:25:00Z',
    '2026-07-07T11:25:00Z'
  )
  ON CONFLICT (id) DO UPDATE SET
    author_id = EXCLUDED.author_id,
    title = EXCLUDED.title,
    body = EXCLUDED.body,
    image_urls = EXCLUDED.image_urls,
    status = EXCLUDED.status,
    audit_status = EXCLUDED.audit_status,
    audit_provider = EXCLUDED.audit_provider,
    audit_reason = EXCLUDED.audit_reason,
    audit_metadata = EXCLUDED.audit_metadata,
    audited_at = EXCLUDED.audited_at,
    like_count = EXCLUDED.like_count,
    comment_count = EXCLUDED.comment_count,
    view_count = EXCLUDED.view_count,
    save_count = EXCLUDED.save_count,
    metadata = EXCLUDED.metadata,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at;
END $$;

NOTIFY pgrst, 'reload schema';
